  Future<String?> _pickCategory({String? excluded}) async { final value = await showModalBottomSheet<String>(context: context, showDragHandle: true, builder: (_) => SafeArea(child: Column(mainAxisSize: MainAxisSize.min, children: [const ListTile(title: Text('Выбрать подборку', style: TextStyle(fontWeight: FontWeight.w800))), if (excluded != null) ListTile(title: const Text('Неразобранное'), onTap: () => Navigator.pop(context, '__none__')), ..._categories.where((c) => c.id != excluded).map((c) => ListTile(title: Text(c.name), onTap: () => Navigator.pop(context, c.id))), ListTile(title: const Text('Создать подборку'), onTap: () => Navigator.pop(context, '__create__'))]))); if (value == null) return '__cancel__'; if (value == '__create__') { await _createCategory(); return _pickCategory(excluded: excluded); } return value == '__none__' ? null : value; }
  Future<void> _moveOne(ArchiveItem item) async { final target = await _pickCategory(excluded: item.categoryId); if (target == '__cancel__' || target == item.categoryId) return; await widget.repository.upsertItem(item.copyWith(categoryId: target, updatedAt: DateTime.now())); await _reload(); _snack(target == null ? 'Перемещено в Неразобранное' : 'Перемещено'); }
  Future<void> _bulkMove() async { if (_selected.isEmpty) return; final target = await _pickCategory(excluded: _categoryId); if (target == '__cancel__' || target == _categoryId) return; final count = _selected.length; await widget.repository.assignCategory(_selected, target); _selected.clear(); _selectionMode = false; await _reload(); _snack('$count ${_plural(count)} перемещено'); }
  Future<void> _bulkDelete() async { if (_selected.isEmpty) return; final count = _selected.length; final ok = await showDialog<bool>(context: context, builder: (_) => AlertDialog(title: Text('Удалить $count ${_plural(count, deleteForm: true)}?'), content: const Text('Объекты будут удалены из архива.'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Отмена')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('Удалить'))])) ?? false; if (!ok) return; await widget.repository.deleteItems(_selected); _selected.clear(); _selectionMode = false; await _reload(); }
  String _plural(int n, {bool deleteForm = false}) { final x = n.abs() % 100; if (x >= 11 && x <= 14) return 'ссылок'; switch (x % 10) { case 1: return deleteForm ? 'ссылку' : 'ссылка'; case 2: case 3: case 4: return deleteForm ? 'ссылки' : 'ссылки'; default: return 'ссылок'; } }
  void _snack(String text) { if (!mounted) return; ScaffoldMessenger.of(context).hideCurrentSnackBar(); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(text))); }
  void _select(String id) { setState(() { if (_selected.contains(id)) _selected.remove(id); else _selected.add(id); }); }

  @override
  Widget build(BuildContext context) {
    final title = _categoryId == null ? 'Неразобранное' : _categories.firstWhereOrNull((c) => c.id == _categoryId)?.name ?? 'Подборка';
    return Scaffold(
      appBar: AppBar(leading: _selectionMode ? IconButton(onPressed: () => setState(() { _selectionMode = false; _selected.clear(); }), icon: const Icon(Icons.close)) : null, title: _selectionMode ? Text('Выбрано: ${_selected.length}') : Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Мой архив', style: TextStyle(fontWeight: FontWeight.w900)), Text(title, style: Theme.of(context).textTheme.labelMedium)]), actions: [if (!_selectionMode) ...[IconButton(tooltip: 'Умная сортировка', onPressed: _openSmartSort, icon: const Icon(Icons.auto_awesome_outlined)), IconButton(tooltip: 'Сортировать', onPressed: () => setState(() => _selectionMode = true), icon: const Icon(Icons.checklist_outlined))]],
      drawer: _buildDrawer(), floatingActionButtonLocation: FloatingActionButtonLocation.startFloat, floatingActionButton: _selectionMode ? null : FloatingActionButton.extended(onPressed: _addDialog, icon: const Icon(Icons.add), label: const Text('Добавить ссылку')),
      bottomNavigationBar: _selectionMode && _selected.isNotEmpty ? SafeArea(child: Padding(padding: const EdgeInsets.all(10), child: Row(children: [Expanded(child: OutlinedButton.icon(onPressed: _bulkDelete, icon: const Icon(Icons.delete_outline), label: const Text('Удалить'))), const SizedBox(width: 8), Expanded(child: FilledButton.icon(onPressed: _bulkMove, icon: const Icon(Icons.drive_file_move_outline), label: Text(_categoryId == null ? 'В подборку' : 'Переместить')))]))) : null,
      body: _loading ? const Center(child: CircularProgressIndicator()) : _loadError != null ? _errorBody() : _items.isEmpty ? _emptyBody(title) : RefreshIndicator(onRefresh: _reload, child: GridView.builder(padding: const EdgeInsets.fromLTRB(12, 12, 12, 110), gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2, crossAxisSpacing: 12, mainAxisSpacing: 12, childAspectRatio: .74), itemCount: _items.length, itemBuilder: (_, index) { final item = _items[index]; return ArchiveCard(item: item, selected: _selected.contains(item.id), selectionMode: _selectionMode, onTap: () => _selectionMode ? _select(item.id) : _openDetail(item), onAction: () => _moveOne(item)); })),
    );
  }
